<a href="https://colab.research.google.com/github/khanhkhanhlele/ML-lab/blob/main/Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Làm quen với Python


In [ ]:
a = 1
b = 2.0
c = a + b
c

3.0

In [ ]:
f_num = float("2018")
int_num = int("2018")
year = str(2018)
f_num, int_num, year

(2018.0, 2018, '2018')

In [ ]:
name = 'summer' + str(2018)
name2 = '1' * 5
name3 = 'Data {} {}'.format("Science", 2018)
name, name2, name3

('summer2018', '11111', 'Data Science 2018')

In [ ]:
list_1 = name3.split()
list_2 = 'Data--Science--2018'.split('--')
name = '--'.join(list_1)
name2 = 'Data Science'.replace('e','-')
list_1, list_2, name, name2

(['Data', 'Science', '2018'],
 ['Data', 'Science', '2018'],
 'Data--Science--2018',
 'Data Sci-nc-')

In [ ]:
a = ' '.isspace()
b = '\t\t'.isspace()
c = '-'.isspace()
print(a,b,c)
a = 'abcde'.isalpha()
b = 'ab12'.isalpha()
print(a,b)
a = '1234'.isdigit()
b = 'ab12'.isdigit()
print(a,b)

True True False
True False
True False


###list

In [ ]:
a = [1,2,3]
b = range(5)
c = range(1,10,2)
d = range(5,1,-1)
e = [x for x in range(10) if x % 2 == 0]
f = []
f.append("alo")
f.append(123)
a, b, c, d, e, f

range(0, 5)


([1, 2, 3],
 range(0, 5),
 range(1, 10, 2),
 range(5, 1, -1),
 [0, 2, 4, 6, 8],
 ['alo', 123])

In [ ]:
src =  range(10)
a = src[:7]
b = src[3:]
c = src[3:7]
d = src[:-1]
e = src[:-2]
length = len(src)
a, b, c, d, e, length

(range(0, 7), range(3, 10), range(3, 7), range(0, 9), range(0, 8), 10)

In [ ]:
src = ['a', 'b', 20]
obj = list(enumerate(src))
obj

[(0, 'a'), (1, 'b'), (2, 20)]

In [ ]:
exp_1 = 'a' in src
exp_2 = 20 not in src
exp_1, exp_2

(True, False)

In [ ]:
src = [(3, "A"), (2, "C"), (1, "D"), (4, "B")]
src.sort()
print(src)
src.sort(key = lambda a: a[1])
print(src)

[(1, 'D'), (2, 'C'), (3, 'A'), (4, 'B')]
[(3, 'A'), (4, 'B'), (2, 'C'), (1, 'D')]


In [ ]:
src = list(range(5))
del src[3]
src

[0, 1, 2, 4]

In [ ]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
c = list(zip(a, b))
c

[(1, 'a'), (2, 'b'), (3, 'c')]

###tuple

In [ ]:
src = (3, 2, 1)
#src[2] = 5
#không được đổi

### set

In [ ]:
#Tập hợp các phần tử phân biệt
#Thu gọn list có các phần tử trùng lặp

src = [1, 2, 3, 2, 4, 4, 5, 1]
reduce_list = list(set(src))
reduce_list

[1, 2, 3, 4, 5]

###dictionary

In [ ]:
dict_1 = dict()
dict_1['A'] = 1
dict_1['B'] = 2
dict_1

{'A': 1, 'B': 2}

In [ ]:
dict_1.keys()

dict_keys(['A', 'B'])

In [ ]:
dict_1.values()

dict_values([1, 2])

###if, else, loop

In [ ]:
a = 1
if a == 1:
  print(True)
else:
  print(False)

True


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
i = 0
while True:
  i += 1
  if i % 2 == 0:
    print(i)
  if i == 10:
    break

2
4
6
8
10


### read, write file

In [ ]:
with open('file.txt') as f:
  content = f.read()

In [ ]:
with open('file.txt', 'w') as f:
  content = f.write('abc 123')

###try

In [ ]:
try:
  division = 10/0
except ZeroDivisionError:
  print("Division by zero occurs")

Division by zero occurs


###assert

In [ ]:
a = 5
b = 0
# assert b != 0, "a"
# c = a/b

###funtion


In [ ]:
def do_sum(a,b=5):
  def decrease(a):
    return a - 1
  return decrease(a+b)
do_sum(7)

11

###oop

In [ ]:
class Person:
  def __init__(self, name, age, phone_number):
    self._name = name
    self._age = age
    self._phone_number = phone_number
    self._selected_items = []
  def select(self, item):
    self._selected_items.append(item)
  def get_info(self):
    return 'Name: {} \nAge: {} \nPhone number: {}'.format(self._name, self._age, self._phone_number)

In [ ]:
nam = Person("Nam", 16, 123456)
nam.select("Book")
nam.select("Pen")
print(nam._selected_items)
print(nam.get_info())

['Book', 'Pen']
Name: Nam 
Age: 16 
Phone number: 123456


###numpy

In [ ]:
import numpy as np
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 5, 3], [4, 1, 6],[7, 8, 9]])
a1, a2

(array([1, 2, 3]), array([[1, 5, 3],
        [4, 1, 6],
        [7, 8, 9]]))

In [ ]:
a1 + a2
a1 - a2
a1.dot(a2)
a1 / a2
a2.transpose()
np.linalg.inv(a2)

array([[-0.59090909, -0.31818182,  0.40909091],
       [ 0.09090909, -0.18181818,  0.09090909],
       [ 0.37878788,  0.40909091, -0.28787879]])

##Linear Regression

###import

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/x28.txt',header=None, index_col=False,delim_whitespace=True)
#file đã xóa trực tiếp mấy dòng comment
data = data.iloc[:,1:]
data.head()

1   2   3     4     5     6     7   ...    10    11  12  13   14  15        16
0  36  27  71   8.1  3.34  11.4  81.5  ...  42.6  11.7  21  15   59  59   921.870
1  35  23  72  11.1  3.14  11.0  78.8  ...  50.7  14.4   8  10   39  57   997.875
2  44  29  74  10.4  3.21   9.8  81.6  ...  39.4  12.4   6   6   33  54   962.354
3  47  45  79   6.5  3.41  11.1  77.5  ...  50.2  20.6  18   8   24  56   982.291
4  43  35  77   7.6  3.44   9.6  84.6  ...  43.7  14.3  43  38  206  55  1071.289

[5 rows x 16 columns]

In [ ]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [ ]:
X_train, y_train = X[:50], y[:50]
X_test,y_test = X[50:], y[50:]

###feature scaling

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)

###Cross-validation

cách hiểu:

là 1 phương pháp để do sự chính xác của 1 model bằng cách chia model thành k tập $D_1,D_2,...,D_k$. Cho $i$ chạy từ 1 đên $k$, lấy $D_i$ làm tập test, $D\backslash D_i$ làm tập train, thực hiện model, tính loss function trên tập $D_i$ được $L_i$. 

trung bình hàm mất mát của model sẽ được tính bằng: $\frac{1}{k}\sum\limits_{i = 1}^k {{L_i}} $

###get lambda

cách hiểu:

cho lambda chạy từ 0 đến 49, qua phương pháp cross-validation để tìm lambda tối ưu.( được λ)

cho lambda chạy từ λ-1 đến λ+1 (mỗi bước +0.001) tiếp tục áp dụng cross-validation để tìm lambda tối ưu.




In [ ]:
from sklearn.linear_model import Ridge
import numpy as np
from sklearn.model_selection import cross_validate

lam = 0
RRS = 100000000 #khởi tạo giá trị hàm mất mát
for i in range(0,50):
  clf = Ridge(alpha=i)
  scores = cross_validate(clf, X_train, y_train, cv=5,scoring=('neg_mean_squared_error'))
  # cross_validate với model Ridge, chạy trên tập train, k = 5, phương pháp tính là compute RSS
  # trả về list 5 phần tử tương ứng là negative của RRS ứng với mỗi nhóm
  RRS_new = -1 * np.average(scores['test_score']) #tính trung bình của RSS
  #print(RRS_new)
  if RRS > RRS_new:
    RRS = RRS_new
    lam = i

for i in range((lam-1)*1000, (lam+1)*1000):
  clf = Ridge(alpha = i/1000)
  scores = cross_validate(clf, X_train, y_train, cv=5,scoring=('neg_mean_squared_error'))
  RRS_new = -1 * np.average(scores['test_score'])
  #print(RRS_new)
  if RRS > RRS_new:
    RRS = RRS_new
    lam = i/1000

print(lam)

0.755

###train

In [ ]:
clf = Ridge(alpha=lam)
clf.fit(X_train, y_train)
clf.predict(X_test)

array([900.66421176, 926.96412256, 924.8150966 , 916.45220249,
       965.1466827 , 891.69065456, 934.35650943, 914.16036574,
       977.00659239, 945.72271639])

## Tiền xử lý dữ liệu

###tf-idf
dùng thư viện [sau](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)


In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [3]:
print(X)

  (0, 1)	0.46979138557992045
  (0, 2)	0.5802858236844359
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 8)	0.38408524091481483
  (1, 5)	0.5386476208856763
  (1, 1)	0.6876235979836938
  (1, 6)	0.281088674033753
  (1, 3)	0.281088674033753
  (1, 8)	0.281088674033753
  (2, 4)	0.511848512707169
  (2, 7)	0.511848512707169
  (2, 0)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 3)	0.267103787642168
  (2, 8)	0.267103787642168
  (3, 1)	0.46979138557992045
  (3, 2)	0.5802858236844359
  (3, 6)	0.38408524091481483
  (3, 3)	0.38408524091481483
  (3, 8)	0.38408524091481483
